import tempfile
from fpdf import FPDF
import os

class ResumePDF(FPDF):
    def header(self):
        # Add a subtle top bar for branding
        self.set_fill_color(30, 41, 59) # Dark Slate Blue
        self.rect(0, 0, 210, 15, 'F')

def export_to_pdf(name, email, school, degree, skills, bullets):
    pdf = ResumePDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # --- CONTACT HEADER ---
    pdf.set_y(20)
    pdf.set_font("Helvetica", "B", 24)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(0, 12, name.upper(), ln=True, align='L')
    
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(0, 6, f"{email}  |  {school}  |  {degree}", ln=True)
    pdf.ln(5)

    # --- SECTION: SKILLS ---
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(0, 8, "TECHNICAL EXPERTISE", ln=True)
    # The Divider Line
    pdf.set_draw_color(226, 232, 240)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)
    
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(51, 65, 85)
    pdf.multi_cell(0, 6, skills)
    pdf.ln(6)

    # --- SECTION: EXPERIENCE ---
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(0, 8, "PROFESSIONAL EXPERIENCE", ln=True)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)

    pdf.set_font("Helvetica", "", 10)
    for bullet in bullets:
        # Drawing a small "bullet point" circle
        current_y = pdf.get_y()
        pdf.set_fill_color(30, 41, 59)
        pdf.circle(13, current_y + 2.5, 0.5, 'F')
        
        pdf.set_x(16) # Indent the text
        pdf.multi_cell(0, 6, bullet)
        pdf.ln(2)

    # --- FOOTER TAG ---
    pdf.set_y(-20)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(148, 163, 184)
    pdf.cell(0, 10, "Generated by R3sum3OS Diamond Engine", align='C')

    fd, path = tempfile.mkstemp(suffix=".pdf")
    os.close(fd)
    pdf.output(path)
    
    return str(path), True
